services:
  - type: web
    name: meine-react-app
    env: static
    buildCommand: npm cache clean --force && npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: CI
        value: "true"
