services:
  # Frontend Service
  - type: web
    name: meine-react-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: REACT_APP_API_URL
        value: https://render-social-media-max-backend.onrender.com
  
  # Backend Service (falls du es auf Render hostest)
  - type: web
    name: python-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      # Füge hier deine Backend-Umgebungsvariablen hinzu
